# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/Booking.Server.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'
    feedsToUse: select
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Publish API project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Booking.Server.API.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/API'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: Publish API artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/API'
    ArtifactName: 'API'
    publishLocation: 'container'

- task: DotNetCoreCLI@2
  displayName: Publish DB project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Booking.Server.DB.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/DB'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: Publish DB artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/DB'
    ArtifactName: 'DB'
    publishLocation: 'container' 

- task: DotNetCoreCLI@2
  displayName: Publish Test project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/Booking.Server.Test.csproj'
    arguments: '--no-build --no-self-contained --output $(Build.ArtifactStagingDirectory)/Test'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishPipelineArtifact@1
  displayName: Publish Test artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/Test'
    ArtifactName: 'Test'
    publishLocation: 'container' 