# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solutionDir: 'booking-api/Booking.Server'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    version: 6.0.x
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    workingDirectory: '$(solutionDir)'

- script: dotnet build --no-restore
  displayName:'Build'
  workingDirectory: '$(solutionDir)'

- script: dotnet test --no-build --verbosity normal
  displayName:'Test'
  workingDirectory: '$(solutionDir)'

- task: DotNetCoreCLI@2
  displayName: Publish API project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**Booking.Server.API.csproj'
    arguments: '--no-build --no-self-contained --output $(Build.ArtifactStagingDirectory)/API'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(solutionDir)'

- task: PublishPipelineArtifact@1
  displayName: Publish API artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/API'
    ArtifactName: 'API'
    publishLocation: 'container'
    workingDirectory: '$(solutionDir)'

- task: DotNetCoreCLI@2
  displayName: Publish DB project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**Booking.Server.DB.csproj'
    arguments: '--no-build --no-self-contained --output $(Build.ArtifactStagingDirectory)/DB'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(solutionDir)'

- task: PublishPipelineArtifact@1
  displayName: Publish DB artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/DB'
    ArtifactName: 'DB'
    publishLocation: 'container' 
    workingDirectory: '$(solutionDir)'

- task: DotNetCoreCLI@2
  displayName: Publish Test project
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**Booking.Server.Test.csproj'
    arguments: '--no-build --no-self-contained --output $(Build.ArtifactStagingDirectory)/Test'
    zipAfterPublish: false
    modifyOutputPath: false
    workingDirectory: '$(solutionDir)'

- task: PublishPipelineArtifact@1
  displayName: Publish Test artifact
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/Test'
    ArtifactName: 'Test'
    publishLocation: 'container' 
    workingDirectory: '$(solutionDir)'