name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./booking-api/Booking.Server

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{env.working-directory}}
    - name: Publish
      run: dotnet publish
      working-directory: ${{env.working-directory}}
    - name: Upload API Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: API
        path: /home/runner/work/sample-applications/sample-applications/booking-api/Booking.Server/Booking.Server.API/bin/Debug/net6.0/publish/
    
